services:
  - type: web
    name: robethood
    env: python
    region: frankfurt
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ROBETHOOD_API_KEY
        value: 2b64543f-b30f-4c56-b6ca-110bbfd9ed30
      - key: ROBETHOOD_API_URL
        value: https://www.robethood.com
    autoDeploy: true
