services:
  - type: web
    name: robethood
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ROBETHOOD_API_KEY
        sync: false
      - key: ROBETHOOD_API_URL
        value: https://www.robethood.com
