services:
  - type: web
    name: instaapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn instaapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
